# 基础设置
title: "Clarity-Vermilion Heartsea"       # 网站标题
description: "一片精神旷野，一片心灵之海"   # 网站副标题
url: "https://ever-luv.github.io"         # 您的网站URL
baseurl: ""                               # 项目子路径（若无则留空）
lang: zh-CN

# 作者信息
author:
  name: "sun-zx"
  github: "ever-luv"
  email: "2500574696@qq.com"

# 主题设置
theme: minima
plugins:
  - jekyll-paginate

# 导航菜单
navbar:
  - name: "首页"
    url: "/"
  - name: "文章列表"
    url: "/posts"
  - name: "留言板"
    url: "/guestbook"
  - name: "关于"
    url: "/about"
  
# 分页设置
paginate: 10
paginate_path: "/page:num"

# Markdown解析
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
