# Jekyll 基本配置
title: "我的个人博客"       # 站点标题
description: "记录技术与生活"  # 站点描述
url: "https://yourusername.github.io"  # 你的 GitHub Pages 地址
baseurl: ""  # 如果项目在子目录，填写子目录路径 (如 "/blog")

# 作者信息
author:
  name: "张三"
  email: "your-email@example.com"
  github: "yourusername"
  twitter: "yourtwitter"

# 构建设置
theme: minima  # 使用 Jekyll 默认主题
plugins:       # 启用的插件
  - jekyll-feed
  - jekyll-seo-tag

# 排除文件/目录
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/
  - vendor/

# 默认值设置
defaults:
  - scope:
      path: ""  # 所有文件
    values:
      layout: "default"  # 默认布局

  - scope:
      path: "_posts"    # 文章目录
      type: posts
    values:
      layout: "post"    # 文章专用布局
      comments: true    # 默认开启评论

# Markdown 处理器
markdown: kramdown  # GitHub Pages 默认使用 kramdown

# kramdown 设置
kramdown:
  input: GFM          # 使用 GitHub Flavored Markdown
  syntax_highlighter: rouge  # 代码高亮引擎

# 分页设置
paginate: 5           # 每页显示文章数
paginate_path: "/blog/page:num"  # 分页路径

# 自定义变量
social_links:         # 社交媒体链接
  - name: GitHub
    url: https://github.com/yourusername
  - name: Twitter
    url: https://twitter.com/yourtwitter

# GitHub Pages 特定设置（自动构建）
remote_theme: pages-themes/minima@v0.2.0  # 使用远程主题（可选）

# 评论系统设置（示例）
disqus:
  shortname: your-disqus-shortname  # Disqus 账户名

# 谷歌分析（示例）
google_analytics: UA-XXXXX-X  # 替换为你的跟踪ID

# 时间格式
timezone: Asia/Shanghai  # 设置时区
