# 基础设置
title: "Clarity-Vermilion Heartsea"                       # 网站标题
description: "一片精神旷野，一片心灵之海"  # 网站副标题
url: ""    # 您的网站URL
baseurl: ""                             # 项目子路径（若无则留空）

# 主题设置
theme: minima                           # 使用GitHub Pages默认主题
minima:
  skin: light                          # 浅色主题
  

# 自定义导航
navbar:
  - name: "首页"
    url: "/"
  - name: "文章列表"
    url: "/posts"
  - name: "留言板"
    url: "/guestbook"
  - name: "关于"
    url: "/about"

# 布局设置
collections:
  posts:
    output: true
    permalink: /:year/:month/:title.html

# Markdown解析
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false

# 分页设置
paginate: 9                            # 每页显示9篇文章（3×3布局）
paginate_path: ""             # 分页路径格式
