# 网站设置
title: "Clarity-Vermilion Heartsea"
email: 2500574696@qq.com
description: "精神旷野，心灵之海"
baseurl: "" # 子路径，例如 /blog
url: "https://ever-luv.github.io" # 你的 GitHub Pages 网址
github_username: ever-luv

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# 分页
paginate: 10
paginate_path: "/page:num/"

# 插件
plugins:
  - jekyll-paginate
  - jekyll-feed

# 默认值
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
